package org.example.tears.Enums;

public enum NotificationType {

    REQUEST_CREATED,
    REQUEST_CANCELLED,
    REQUEST_STATUS_CHANGED,
    REQUEST_ASSIGNED,
    REQUEST_DELIVERED,

    QUOTATION_CREATED,
    QUOTATION_SENT,
    QUOTATION_UPDATED,

    PAYMENT_REQUIRED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,

    APPOINTMENT_CONFIRMED,
    APPOINTMENT_RESCHEDULED,
    APPOINTMENT_CANCELLED,

    REPORT_ATTACHED,
    CAR_RESEIVE_ATTACHED,

    SERVICE_STARTED,
    SERVICE_COMPLETED,

    CHAT_MESSAGE_RECEIVED,

    COUPON_AVAILABLE,

    SUPPORT_TICKET_CREATED,
    SUPPORT_TICKET_ACCEPTED,
    SUPPORT_TICKET_SOLVED,

    WARRANTY_CREATED,
    WARRANTY_RECEIVING_CONFIRMED,
    WARRANTY_STATUS_UPDATED,
    WARRANTY_APPROVED,
    WARRANTY_RECEIVED,
    WARRANTY_REJECTED,

    SYSTEM_ANNOUNCEMENT
}